# Generated by Django 4.2.21 on 2025-05-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فایل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(upload_to='uploaded_files/', verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('other', 'سایر')], max_length=10, verbose_name='نوع فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'فایل آپلودی',
                'verbose_name_plural': 'فایل\u200cهای آپلودی',
            },
        ),
    ]
