# Generated by Django 5.1.2 on 2025-06-03 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='اندازه فایل (بایت)'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12, verbose_name='قیمت (ریال)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدیر پروژه'),
        ),
    ]
