# Generated by Django 5.1.2 on 2025-06-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_file_size_uploadedfile_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='رایگان؟'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت (ریال)'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='project_manager',
            field=models.CharField(default=1, max_length=255, verbose_name='مدیر پروژه'),
            preserve_default=False,
        ),
    ]
