# Generated by Django 5.1.2 on 2025-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_is_free_alter_uploadedfile_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
    ]
