# Generated by Django 4.2.21 on 2025-05-29 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.uploadedfile', verbose_name='فایل سفارش داده\u200cشده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'unique_together': {('user', 'file')},
            },
        ),
    ]
